name: First GithubActionsWorkflow

on:
  # manually trigger the workflow
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello with a single shell command
        run: echo "Hello, World!"

      - name: Run a multi-line script
        run: |
          echo "This is a multi-line script."
          echo "You can run multiple commands here."
          echo "GitHub Actions makes it easy to automate your workflows!"
          sleep 3

  second_job:
    runs-on: macos-latest
    needs: first_job
    steps:
      - name: Say hello again
        run: echo "Hello again from the second job and i am running on MAC OS!"